version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - image_templates:
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=hooky"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source=https://github.com/virtuallytd/hooky"

  - image_templates:
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-arm64"
    goarch: arm64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=hooky"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source=https://github.com/virtuallytd/hooky"

docker_manifests:
  - name_template: "ghcr.io/virtuallytd/hooky:{{ .Version }}"
    image_templates:
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-amd64"
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-arm64"

  - name_template: "ghcr.io/virtuallytd/hooky:latest"
    image_templates:
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-amd64"
      - "ghcr.io/virtuallytd/hooky:{{ .Version }}-arm64"
